services:
  flux-node:
    image: ghcr.io/kukumi1/flux-panel-plus/node:${FLUX_VERSION:-latest}
    container_name: flux-node
    network_mode: host
    restart: unless-stopped
    volumes:
      - ~/.flux:/etc/node
    environment:
      - PANEL_ADDR=http://PANEL_IP:6366
      - SECRET=NODE_SECRET
